### ISSUE TITLE
Example dataset down?

### ISSUE THREAD

**Issue by abey79** [Pix4D/opf-spec#12]
I just noticed that the Amazon buckets containing the example dataset (e.g. https://support.pix4d.com/hc/en-us/articles/360000235126#OPF3) appears to be down. The link returns this error:

<img width="601" alt="image" src="https://github.com/user-attachments/assets/58d81414-7cd7-483c-939f-51be9bf4a41a">

Is that a temporary outage? Or has the location changed?

**Comment by jamesdynes** [comment]
@abey79 thanks for reporting this. We've been rearranging some data and had missed updating this support article.

The link should now be correct, can you double check?

**Comment by abey79** [comment]
Thanks for the quick answer. It seems that only _some_ of the links were updated (the top ones, not the bottom ones):

The updated links do work for me 👍🏻 

<img width="609" alt="image" src="https://github.com/user-attachments/assets/770fba90-7934-4146-a2f8-da7cf91dac95">

**Comment by jamesdynes** [comment]
Thanks, hopefully we've fixed the links on the second attempt. I don't see the deprecated bucket referenced now in the page.
